/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itq.formularios;

import com.itq.enumeraciones.TipoOperacionEnum;

/**
 *
 * 
 */
public class JfrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrPrincipal
     */
    public JfrPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmnBarra = new javax.swing.JMenuBar();
        jmnArchivo = new javax.swing.JMenu();
        jmnSalir = new javax.swing.JMenuItem();
        jmnCliente = new javax.swing.JMenu();
        jmnAgregarCliente = new javax.swing.JMenuItem();
        jmnVerCliente = new javax.swing.JMenuItem();
        jmnProducto = new javax.swing.JMenu();
        jmnAgregarProducto = new javax.swing.JMenuItem();
        jmnVerProducto = new javax.swing.JMenuItem();
        jmnFacturacion = new javax.swing.JMenu();
        jmnFacturar = new javax.swing.JMenuItem();
        jmnReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmnArchivo.setText("Archivo");

        jmnSalir.setText("Salir");
        jmnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSalirActionPerformed(evt);
            }
        });
        jmnArchivo.add(jmnSalir);

        jmnBarra.add(jmnArchivo);

        jmnCliente.setText("Clientes");

        jmnAgregarCliente.setText("Agregar");
        jmnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAgregarClienteActionPerformed(evt);
            }
        });
        jmnCliente.add(jmnAgregarCliente);

        jmnVerCliente.setText("Ver");
        jmnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnVerClienteActionPerformed(evt);
            }
        });
        jmnCliente.add(jmnVerCliente);

        jmnBarra.add(jmnCliente);

        jmnProducto.setText("Productos");

        jmnAgregarProducto.setText("Agregar");
        jmnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAgregarProductoActionPerformed(evt);
            }
        });
        jmnProducto.add(jmnAgregarProducto);

        jmnVerProducto.setText("Ver");
        jmnVerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnVerProductoActionPerformed(evt);
            }
        });
        jmnProducto.add(jmnVerProducto);

        jmnBarra.add(jmnProducto);

        jmnFacturacion.setText("Facturacion");

        jmnFacturar.setText("Facturar");
        jmnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnFacturarActionPerformed(evt);
            }
        });
        jmnFacturacion.add(jmnFacturar);

        jmnReportes.setText("Reportes");
        jmnFacturacion.add(jmnReportes);

        jmnBarra.add(jmnFacturacion);

        setJMenuBar(jmnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAgregarClienteActionPerformed
        JfrCliente formularioCliente = new JfrCliente();
        formularioCliente.setTipoOperacion(TipoOperacionEnum.AGREGAR);
        formularioCliente.setVisible(true);
    }//GEN-LAST:event_jmnAgregarClienteActionPerformed

    private void jmnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVerClienteActionPerformed
        JfrListadorCliente formularioListadorCliente = new JfrListadorCliente();
        formularioListadorCliente.setVisible(true);
        formularioListadorCliente.cargar();
    }//GEN-LAST:event_jmnVerClienteActionPerformed

    private void jmnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAgregarProductoActionPerformed
        JfrProducto formularioProducto = new JfrProducto();
        formularioProducto.setTipoOperacion(TipoOperacionEnum.AGREGAR);
        formularioProducto.setVisible(true);
    }//GEN-LAST:event_jmnAgregarProductoActionPerformed

    private void jmnVerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVerProductoActionPerformed
        JfrListadorProducto formularioListadorProducto = new JfrListadorProducto();
        formularioListadorProducto.setVisible(true);
        formularioListadorProducto.cargar();
    }//GEN-LAST:event_jmnVerProductoActionPerformed

    private void jmnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmnSalirActionPerformed

    private void jmnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnFacturarActionPerformed
        JfrFacturacion formularioFacturacion = new JfrFacturacion();
        formularioFacturacion.setVisible(true);
    }//GEN-LAST:event_jmnFacturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jmnAgregarCliente;
    private javax.swing.JMenuItem jmnAgregarProducto;
    private javax.swing.JMenu jmnArchivo;
    private javax.swing.JMenuBar jmnBarra;
    private javax.swing.JMenu jmnCliente;
    private javax.swing.JMenu jmnFacturacion;
    private javax.swing.JMenuItem jmnFacturar;
    private javax.swing.JMenu jmnProducto;
    private javax.swing.JMenuItem jmnReportes;
    private javax.swing.JMenuItem jmnSalir;
    private javax.swing.JMenuItem jmnVerCliente;
    private javax.swing.JMenuItem jmnVerProducto;
    // End of variables declaration//GEN-END:variables
}
