/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itq.formularios;

import com.itq.datos.ProductoDao;
import com.itq.enumeraciones.TipoOperacionEnum;
import com.itq.modelo.ProductoModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class JfrProducto extends javax.swing.JFrame {
    private TipoOperacionEnum tipoOperacion;
    /**
     * Creates new form JfrProducto
     */
    public JfrProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblCodigoBarras = new javax.swing.JLabel();
        jtxCodigoBarras = new javax.swing.JTextField();
        jlbNombreProducto = new javax.swing.JLabel();
        jtxNombreProducto = new javax.swing.JTextField();
        jlbPrecio = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jtxPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jblCodigoBarras.setText("Codigo Barras");

        jlbNombreProducto.setText("Nombre Producto");

        jlbPrecio.setText("Precio");

        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblCodigoBarras)
                    .addComponent(jlbNombreProducto)
                    .addComponent(jlbPrecio))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtCancelar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxCodigoBarras)
                            .addComponent(jtxNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCodigoBarras)
                    .addComponent(jtxCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombreProducto)
                    .addComponent(jtxNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrecio)
                    .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtGuardar)
                    .addComponent(jbtCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        
        boolean validacion = validar();
        if(validacion==false){
            return;
        }
        
        ProductoDao productoDao = new ProductoDao();
        ProductoModel producto = new ProductoModel();
        String codigoBarras = jtxCodigoBarras.getText();
        String nombre = jtxNombreProducto.getText();
        String strPrecio = jtxPrecio.getText();
        double precio = Double.parseDouble(strPrecio);
        
        producto.setCodigoBarras(codigoBarras);
        producto.setNombre(nombre);
        producto.setPrecio(precio);
        
        if(tipoOperacion==TipoOperacionEnum.AGREGAR)
        {
            productoDao.agregar(producto);
        }else if(tipoOperacion==TipoOperacionEnum.ACTUALIZAR){
            productoDao.actualizar(producto);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbtGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblCodigoBarras;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JLabel jlbNombreProducto;
    private javax.swing.JLabel jlbPrecio;
    private javax.swing.JTextField jtxCodigoBarras;
    private javax.swing.JTextField jtxNombreProducto;
    private javax.swing.JTextField jtxPrecio;
    // End of variables declaration//GEN-END:variables

    public void setTipoOperacion(TipoOperacionEnum tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
        switch(this.tipoOperacion)
        {
            case ACTUALIZAR:
                jtxCodigoBarras.setEditable(false);
                break;
            case AGREGAR:
                jtxCodigoBarras.setEditable(true);
                break;
            default:
        }
    }
    
    public void cargar(String codigoBarras){
        ProductoDao productoDao = new ProductoDao();
        List<ProductoModel> productos = productoDao.buscar(codigoBarras);
        ProductoModel producto = productos.get(0);
        jtxCodigoBarras.setText(producto.getCodigoBarras());
        jtxNombreProducto.setText(producto.getNombre());
        double precio = producto.getPrecio();
        jtxPrecio.setText(String.valueOf(precio));
    }
    
    private boolean validar(){
        if(jtxCodigoBarras.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"El codigo de barras es requerida");
            return false;
        }
        if(jtxNombreProducto.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"El nombre del producto es requerida");
            return false;
        }
        String strPrecio = jtxPrecio.getText();
        if(strPrecio.trim().equals("")){
            JOptionPane.showMessageDialog(this,"El precio es requerida");
            return false;
        }
        
        boolean esNumero = strPrecio.matches("-?\\d+(\\.\\d+)?");        
        if(esNumero==false){
            JOptionPane.showMessageDialog(this,"Ingrese un numero valido para el precio");
            return false;
        }
        
        return true;
    }
}
