/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itq.formularios;

import com.itq.datos.ClienteDao;
import com.itq.enumeraciones.TipoOperacionEnum;
import com.itq.modelo.ClienteModel;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class JfrSelectorCliente extends javax.swing.JFrame {

    private JfrFacturacion formularioFacturacion;
    /**
     * Creates new form JfrSelectorCliente
     */
    public JfrSelectorCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplPanelBusqueda = new javax.swing.JPanel();
        jbtBuscar = new javax.swing.JButton();
        jlbCedula = new javax.swing.JLabel();
        jTxCedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbClientes = new javax.swing.JTable();
        jbtSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jplPanelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplPanelBusqueda.setName(""); // NOI18N

        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jlbCedula.setText("Cedula");

        javax.swing.GroupLayout jplPanelBusquedaLayout = new javax.swing.GroupLayout(jplPanelBusqueda);
        jplPanelBusqueda.setLayout(jplPanelBusquedaLayout);
        jplPanelBusquedaLayout.setHorizontalGroup(
            jplPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPanelBusquedaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplPanelBusquedaLayout.setVerticalGroup(
            jplPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplPanelBusquedaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jplPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCedula)
                    .addComponent(jTxCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbClientes);

        jbtSeleccionar.setText("Seleccionar");
        jbtSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jplPanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSeleccionar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jplPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtSeleccionar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        ClienteDao clienteDao = new ClienteDao();
        String cedula = jTxCedula.getText();
        List<ClienteModel> clientes = clienteDao.buscar(cedula);
        DefaultTableModel modeloTabla = (DefaultTableModel) jtbClientes.getModel();
        
        modeloTabla.setRowCount(0);
        
        for(ClienteModel cliente : clientes){
            Object[] row = new Object[3];
            row[0] = cliente.getCedula();
            row[1] = cliente.getNombre();
            row[2] = cliente.getApellido();
            modeloTabla.addRow(row);
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSeleccionarActionPerformed
        int rowSeleccionado = jtbClientes.getSelectedRow();        
        DefaultTableModel modeloTabla = (DefaultTableModel) jtbClientes.getModel();
        String cedula =  (String) modeloTabla.getValueAt(rowSeleccionado, 0);
        ClienteDao clienteDao = new ClienteDao();
        List<ClienteModel> clientes = clienteDao.buscar(cedula);
        ClienteModel cliente = clientes.get(0);
        formularioFacturacion.seleccionarCliente(cliente);
        this.dispose();
    }//GEN-LAST:event_jbtSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrSelectorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxCedula;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtSeleccionar;
    private javax.swing.JLabel jlbCedula;
    private javax.swing.JPanel jplPanelBusqueda;
    private javax.swing.JTable jtbClientes;
    // End of variables declaration//GEN-END:variables
  public void cargar(){
        ClienteDao clienteDao = new ClienteDao();
        List<ClienteModel> clientes = clienteDao.listarTodos();
        DefaultTableModel modeloTabla = (DefaultTableModel) jtbClientes.getModel();
        for(ClienteModel cliente : clientes){
            Object[] row = new Object[3];
            row[0] = cliente.getCedula();
            row[1] = cliente.getNombre();
            row[2] = cliente.getApellido();
            modeloTabla.addRow(row);
        }
    }
  public void setFormularioFacturacion(JfrFacturacion formularioFacturacion){
      this.formularioFacturacion = formularioFacturacion;
  }
}
